# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) 
  displayName: 'dotnet build $(buildConfiguration)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN(31567d68-89c7-4363-80f2-f5e70f795467)'
    appType: 'webAppLinux'
    appName: 'stoy-and-deploy'
    package: '$(System.DefaultWorkingDirectory)/**/publish'
    runtimeStack: 'DOTNETCORE|2.2'